######################################################################
# Automatically generated by qmake (3.0) Tue Jul 31 14:27:00 2018
######################################################################

TEMPLATE = app
TARGET = dbus
INCLUDEPATH += .
INCLUDEPATH += /auto/spvss-evo-infra/mds-odci/ws/qt_artifactory/jenkins-qt_platform_astro_aophysb2_ivp-37-aophysb2_ivp/NDS/include/dbus-c++-1

QT -= gui
QT -= core

LIBS += -L/auto/spvss-evo-infra/mds-odci/ws/qt_artifactory/jenkins-qt_platform_astro_aophysb2_ivp-37-aophysb2_ivp/NDS/lib -ldbus-c++-1 -ldbus-1

# Input
HEADERS += ip_xmpp_voice_proxy.h \
           voice_interface.h \
	   dbus_voice_interface.h
SOURCES += main.c \
	   dbus_voice_interface.cpp
